# Generated by Django 2.1.7 on 2019-03-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190322_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='position',
            field=models.CharField(default='CTO', max_length=255),
            preserve_default=False,
        ),
    ]
